### ISSUE TITLE
Lita is unable to resolve

### ISSUE THREAD

**Issue by dalekurt** [esigler/lita-dig#2]
Hi, I have lita running on Heroku and integrated with Slack. I'm having an issue where `lita dig github.com` where is returns `Unable to resolve <http://github.com|github.com>`.

Is this an issue I can fix?

**Comment by esigler** [comment]
Howdy!  Thanks for the bug report - I'll try to reproduce it shortly.  Did you do anything specific when launching Lita on Heroku?

**Comment by dalekurt** [comment]
No, there was nothing special about it.

**Comment by geefinator** [comment]
Just to add, I get this too, however i get this when using the slack adapter to do any DNS lookup at all.  I filed an issue with the adapter dev: https://github.com/kenjij/lita-slack/issues/37   So I don't think this is an issue with the plugin :)

**Comment by Beastcraft** [comment]
@geefinator @dalekurt Did you try to resolve the domain on the host itself (using dig)? lita-dig is using 8.8.8.8 as the default resolver. Check if you can reach that or try out a different resolver, reachable by your network.

@esigler Wouldn't it be nice, to configure the default resolver in lita_config.rb? I'll make the changes and fill a pull request, when I get to it :-)

**Comment by esigler** [comment]
@Beastcraft Indeed, I'd +1 that PR.  The fixed default resolver was an issue of expediency and should definitely be made more flexible.

**Comment by esigler** [comment]
@dalekurt Yeah, looking at it seems like this is an issue with Slack passing along a bad value, I think https://github.com/kenjij/lita-slack/pull/35 will address it once that's merged.

**Comment by wjimenez5271** [comment]
Yea I'm seeing this issue too, my litabot is sad :-(

**Comment by esigler** [comment]
Resolver can be configured now, lita-slack has been updated, and a new DNS gem is in use - closing this out now.
