### ISSUE TITLE
Allow for output formatting in various Lita adapters

### ISSUE THREAD

**Issue by esigler** [esigler/lita-dig#6]
It would be great to get output formatting for the various Lita adapters (Slack, Hipchat, etc) via templates.

**Comment by brodock** [comment]
I can send you a PR for "normal" and "slack" templates if you wish... I don't have access to any hipchat server to test :/

**Comment by esigler** [comment]
@brodock Sure, that would be fantastic!

**Comment by esigler** [comment]
Fixed in #7 !
